name: Destroy Infrastructure

# `workflow_dispatch` means this workflow runs when triggered manually (not automatically)
on:
  workflow_dispatch:

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        # On init the backend will read the remote state from S3

      - name: Terraform Destroy
        run: terraform destroy -auto-approve